#!/bin/bash

PIDFILE="$OPENSHIFT_DATA_DIR/worker.pid"

if [ -e "$PIDFILE" ]; then
	PID="$(<$PIDFILE)"

	if [ -z "$PID" ]; then
		echo 'Worker pid file is empty'
	else
		if kill -0 $PID &>/dev/null; then
			echo "Worker is running (PID $PID)"
		else
			echo "Worker is stoped or stalled (PID $PID)"
		fi
	fi
else
	echo "Worker is stopped"
fi
